spring.application.name=mascotas

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/mascotas-data-base}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

# mostrar las consultas SQL
spring.jpa.show-sql=true

# configuracion para que actualice el esquema
spring.jpa.hibernate.ddl-auto=update

# optimizar la base de datos
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect